#!/usr/bin/env python3
"""Generate docs/issues/RED_TAG.md from canonical issue records."""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
ISSUES_DIR = REPO_ROOT / "docs" / "issues"
RED_TAG_FILE = ISSUES_DIR / "RED_TAG.md"

FIELD_LINE_PATTERN = re.compile(r"^-\s+\*\*(.+?):\*\*\s*(.*)$")
STATUS_OPENISH = {"open", "in_progress", "blocked"}


def parse_issue_fields(issue_text: str) -> dict[str, str]:
    fields: dict[str, str] = {}
    for line in issue_text.splitlines():
        match = FIELD_LINE_PATTERN.match(line.strip())
        if match:
            fields[match.group(1).strip()] = match.group(2).strip()
    return fields


def list_red_open_issues() -> list[tuple[str, str, str]]:
    rows: list[tuple[str, str, str]] = []
    for issue_path in sorted(ISSUES_DIR.glob("ISSUE-*.md")):
        text = issue_path.read_text(encoding="utf-8")
        fields = parse_issue_fields(text)

        issue_id = fields.get("ID", "").strip()
        title = fields.get("Title", "").strip()
        status = fields.get("Status", "").strip().lower()
        severity = fields.get("Severity", "").strip().lower()

        if severity != "red" or status not in STATUS_OPENISH or not issue_id:
            continue

        if not title:
            title = issue_path.stem

        rows.append((issue_id, title, issue_path.name))

    rows.sort(key=lambda row: row[0])
    return rows


def render_red_tag(rows: list[tuple[str, str, str]]) -> str:
    lines = [
        "# Red-Tag Issues",
        "",
        "This index is generated from `docs/issues/ISSUE-*.md` entries with `Severity: red` and open-like `Status` values (`open`, `in_progress`, `blocked`).",
        "",
        "Do not edit this file directly. Regenerate it with:",
        "",
        "```bash",
        "python scripts/generate_red_tag_index.py",
        "```",
        "",
        "## Active",
        "",
    ]

    if not rows:
        lines.append("- _None._")
    else:
        for issue_id, title, filename in rows:
            lines.append(f"- [{issue_id} — {title}](./{filename})")

    lines.append("")
    return "\n".join(lines)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if docs/issues/RED_TAG.md differs from generated content.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    expected = render_red_tag(list_red_open_issues())

    if args.check:
        current = RED_TAG_FILE.read_text(encoding="utf-8") if RED_TAG_FILE.exists() else ""
        if current != expected:
            print("docs/issues/RED_TAG.md is out of date. Run: python scripts/generate_red_tag_index.py", file=sys.stderr)
            return 1
        print("docs/issues/RED_TAG.md is up to date.")
        return 0

    RED_TAG_FILE.write_text(expected, encoding="utf-8")
    print(f"Wrote {RED_TAG_FILE.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
